name: Build and Export IPA (Manual + No Sign)

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: '构建类型'
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - release
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        run: |
          xcodebuild -workspace YourProject.xcworkspace -scheme YourScheme \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-unsigned-${{ github.event.inputs.build_type }}.ipa
          path: build/YourApp.ipa
