name: Build and Export Unsigned IPA

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # 添加手动触发工作流的配置

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print project info
        run: |
          echo "::debug::Xcode version:"
          xcodebuild -version | while IFS= read -r line; do echo "::debug::$line"; done
          echo "::debug::Swift version:"
          swift --version | while IFS= read -r line; do echo "::debug::$line"; done

      - name: Build the project with Swift 5.0
        run: |
          # 重定向标准输出到 /dev/null，只保留标准错误输出
          xcodebuild -project Qin.xcodeproj -scheme "Qin (iOS)" -sdk iphoneos -configuration Release clean build \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO \
            -derivedDataPath $PWD/build \
            SWIFT_VERSION=5.0 > /dev/null

      - name: Create Payload directory
        run: |
          mkdir -p $PWD/build/Payload

      - name: Copy .app to Payload
        run: |
          cp -r $PWD/build/Build/Products/Release-iphoneos/Qin.app $PWD/build/Payload/

      - name: Zip Payload to IPA
        run: |
          cd $PWD/build
          zip -r QinMusic.ipa Payload

      - name: Upload IPA as artifact
        uses: actions/upload-artifact@v4
        with:
          name: QinMusic.ipa
          path: build/QinMusic.ipa
